# Generated by Django 3.0.5 on 2021-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('maritial_status', models.CharField(max_length=50)),
                ('training_count', models.PositiveIntegerField()),
                ('training_by', models.CharField(max_length=200)),
            ],
        ),
    ]
