# Generated by Django 3.0.5 on 2021-11-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
