# Generated by Django 3.0.5 on 2021-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0002_auto_20211107_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
