# Generated by Django 3.0.5 on 2021-11-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0004_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Police/'),
        ),
    ]
