# Generated by Django 3.0.5 on 2021-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0006_cid_ob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_date', models.DateField()),
                ('criminal_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Criminal/')),
                ('criminal_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('hair_color', models.CharField(max_length=20)),
                ('crime', models.CharField(max_length=500)),
            ],
        ),
    ]
