# Generated by Django 3.0.5 on 2021-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0008_auto_20211108_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='crime_date',
            field=models.CharField(max_length=20),
        ),
    ]
