# Generated by Django 3.0.5 on 2021-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juba', '0010_auto_20211119_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='cid',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cid',
            name='unique_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
